# Colors and true color
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB,alacritty:RGB"

# Clipboard
set -g set-clipboard on

# Mouse
set -g mouse on

# History
set -g history-limit 50000

# Escape delay
set -g escape-time 0

# Numeration windows
set -g base-index 1
setw -g pane-base-index 1

# Recalculation windows number when one window is closed
set -g renumber-windows on

# Vi-mode for copy/paste
setw -g mode-keys vi


# Bind tmux hotkeys
bind c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"


# ----------------------------------------
# Status bar
# ----------------------------------------

set -g status-position bottom

set -g status-style "bg=#000000,fg=#808080"

set -g status-left-length 30
set -g status-right-length 60

set -g status-left "#[fg=#ffffff,bold] #S #[fg=#303030]│"

set -g status-right "#[fg=#606060] %Y-%m-%d #[fg=#ffffff] %H:%M "

setw -g window-status-format "#[fg=#606060] #I:#W "
setw -g window-status-current-format "#[fg=#ffffff,bold] #I:#W "

set -g pane-border-style "fg=#202020"
set -g pane-active-border-style "fg=#ffffff"

set -g message-style "bg=#ffffff,fg=#000000"


# ----------------------------------------
# Enable plugins in tpm 
# ----------------------------------------

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

run '~/.tmux/plugins/tpm/tpm'
